spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

PSP:
  toss:
    url: https://api.tosspayments.com
    secretKey: test_sk_5OWRapdA8ddQz7lJ62WW8o1zEqZK